### ISSUE TITLE
Proposal: no external dependencies in the core

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1139]
We've seen numerous problems with having dependencies on 3-rd party native libraries in the core. This includes difficulties finding and installing latest required versions of all libraries. Additionally, it makes Go-style single-binary deployments harder, as you also need to have the same environment to make the application work.

Our current runtime dependencies are:

- [x] **Boehm GC.** We should make immix a default instead. #1137
- [x] **libunwind.** Include libunwind in the core, build it ourselves, and link statically with it. #1138
- [ ] **RE2.** Finish our port of re2j to Scala and make it the default. #873

**Comment by densh** [comment]
So it looks RE2 is the last man standing on this one.

**Comment by densh** [comment]
Last missing step was fixed in #1498.
