### ISSUE TITLE
Proposal: no undefined behavior 

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1140]
Currently, a number of Scala language features that have strictly defined semantics on JVM but are undefined in Scala Native. While this provides greater flexibility in terms of implementation freedom, it burdens the users with harder to debug crashes. 

To make the situation more manageable we are going to:

- [x] Make null dereferencing deterministically crash with a the stack trace.
   - [x] Field dereferencing on null throws NPE. (PR: #1391)
   - [x] Method call on null throws NPE. (PR: #1394)
   - [x] Array ops throw NPE on null array. (PR: #1394)
   - [x] Throw on null throws NPE instead of original exception. (PR: #1390)
- [x] Make incorrect casts deterministically crash with a stack trace. (PR: #1390)
- [x] Make arithmetics error conditions throw arithmetic exceptions, the same as on JVM. (PRs: #1384 #1385 #1386 #1387)
- [x] NIR's `unreachable` should crash with a stack trace. (PR: #1392)
- [x] Remove NIR's undefined value (PR: #1395)
- [ ] ~~Make stack overflow deterministically crash with a stack trace.~~ (See #1396)

**Comment by densh** [comment]
As of latest master (after #1397 merge) we don't have any expected undefined behavior in the NIR operations except for stack overflows and out-of-memory errors being reported differently than on JVM. I also opened #1396 to track progress on making stack overflows nicer and taking advantage of the fact that we can get rid off stack overflow as a concept altogether.
