### ISSUE TITLE
Interflow

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1278]
This issue is meant to track progress on upstreaming Interflow optimizer. More details can be found in [the original announcement](http://www.scala-native.org/en/latest/blog/interflow.html) and [paper preprint](https://github.com/densh/talks/blob/master/2018-06-16-interflow-preprint-v1.pdf).

Prerequisites:

- [x] LLVM integration
   - [x] use `-flto` to optimize across C/Scala boundary (issue #280, pr #1281)
   - [x] annotate hot paths with inline/noinline to guide flto inlining (pr #1284)
- [x] Library 
   - [x] introduce `scalanative.runtime.Array.compare` intrinsic to replace memcmp call in String.equals  (simplifies partial evaluation, pr #1288)
   - [x] don't use unmanaged pointers for String.hashCode (simplifies partial evaluation, pr #1288)
   - [x] annotate performance-critical parts of the Scala runtime with inline/noinline (pr #1290, #1291)
   - [x] minimize use of top-level fields in Scala library and use methods instead for them (simplifies partial evaluation, pr #1292)
- [x] Compiler infrastructure
    - [x] split out lowering passes from optimizer (pr #1295)
    - [x] semantic reachability analysis (pr #1323)
- [x] NIR 
   - [x] include unwind handler in every instruction (pr #1311)
   - [x] dedicated instructions for field load and store (simplifies partial evaluation, pr #1325)
   - [x] dedicated instructions for local vars (simplifies partial evaluation, pr #1326)
   - [x] dedicated instructions for array operations (simplifies partial evaluation, pr #1331)

Interflow:

- [x] initial infrastructure (pr #1339)
- [x] don't bail out on unsafe ops (pr #1401)
- [x] don't bail out on reflective calls (pr #1402)
- [x] introduce nir checker to verify code before and after interflow (pr #1408)
- [x] conservative inlining to test partial evaluation and partial escape analysis (pr #1411)
- [x] aggresive inlining guided by partial escape analysis (pr #1411)
- [x] do DCE in the same pass as interflow (pr #1437)
- [x] do GVN in the same pass as interflow (pr #1440)
- [x] do Canonicalization in the same pass as interflow (#1442)
- [x] do InstCombine in the same pass as interflow (pr #1444)
- [x] optimize in parallel in debug mode (pr #1465)
- [x] do Polymorphic Inlining in the same pass as interflow (pr #1495)
- [x] add `@nospecialize` and `@nooptimize` annotation (pr #1512)

**Comment by liangfu** [comment]
@densh In my understanding, after this is merged, the generated binary executable should be minimal as well. However, I experienced even the compiled HelloWorld demo you listed [here](http://www.scala-native.org/en/latest/contrib/nir.html) is still much larger than expectation (around 2MB). Is there anyway to further reduce binary executable size to be closer to C programs?

**Comment by densh** [comment]
@liangfu 

1. Interflow is aimed at runtime performance first and foremost, not binary size.

2. We statically link all the libraries by default unlike C which links dynamically. Our binary size is comparable to other languages like Go which also link statically.

3. Currently `nativeMode := "release"` and `nativeLTO := "thin"`, I get the following for hello world on Linux:

```
     VM SIZE                         FILE SIZE
 --------------                   --------------
  61.8%   708Ki .text               708Ki  52.5%
  16.0%   184Ki .rodata             184Ki  13.6%
   0.0%       0 .strtab             151Ki  11.2%
  11.0%   126Ki .dynstr             126Ki   9.4%
   5.0%  57.5Ki .eh_frame          57.5Ki   4.3%
   0.0%       0 .symtab            51.9Ki   3.8%
   3.2%  36.3Ki .dynsym            36.3Ki   2.7%
   1.0%  12.0Ki .eh_frame_hdr      12.0Ki   0.9%
   1.0%  10.9Ki .gnu.hash          10.9Ki   0.8%
   0.3%  3.87Ki .bss                    0   0.0%
   0.3%  3.03Ki .gnu.version       3.03Ki   0.2%
   0.0%     568 [ELF Headers]      2.49Ki   0.2%
   0.1%  1.10Ki .rela.plt          1.10Ki   0.1%
   0.0%       0 [Unmapped]            961   0.1%
   0.1%     768 .plt                  768   0.1%
   0.1%     637 [14 Others]           740   0.1%
   0.0%     544 .dynamic              544   0.0%
   0.0%     512 .gcc_except_table     512   0.0%
   0.0%     400 .got.plt              400   0.0%
   0.0%       0 .shstrtab             290   0.0%
   0.0%     208 .data.rel.ro          208   0.0%
 100.0%  1.12Mi TOTAL              1.32Mi 100.0%
```

If you have any more questions about this lets discuss on gitter.

**Comment by densh** [comment]
@liangfu 

Please see #1545.
