### ISSUE TITLE
NIR format refresh

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1287]
A bucket list of changes to NIR:

- [x] Interflow-related changes #1278
  - [x] include (optional) unwind handler in every let instruction (pr #1311)
  - [x] dedicated instructions for field load and store (pr #1325)
  - [x] dedicated instructions for local vars  (pr #1326)
  - [x] dedicated instructions for array operations (pr #1331)
- [x] Fix method resolution being sensitive to the origin of the method that's being overridden #375 (pr #1323)
- [x] Fix name mangling (pr #1372)
- [x] Remove undefined behavior (issue #1140)
- [x] Add support for location metadata to enable #29 
- [x] Add support for concurrency primitives #1102
- [x] Make binary format more compact #132
