### ISSUE TITLE
MMTk's LXR GC Porting Tracker for Scala Native

### ISSUE THREAD

**Issue by 641bill** [scala-native/scala-native#3382]
Tracker for porting [MMTk](https://www.mmtk.io/)'s [LXR GC](https://users.cecs.anu.edu.au/~steveb/pubs/papers/lxr-pldi-2022.pdf) to Scala Native, which is a significant part of my master's thesis project at LAMP.
The porting of a moving, concurrent GC with a write barrier needs to be scaffolded step by step with logical steps along the pathway to the endpoint: having LXR working.
Here is a list of the logical steps:
- [x] NoGC

- [x] Non-moving Immix

- [x] Moving Immix

- [x] Performance Tuning: Optimizing Allocation (Fast-path allocation)

- [x] First benchmarking

- [ ] Sticky Immix (Write barrier)

- [ ] Concurrent Immix (SATB)

- [ ] LXR

**Comment by ekrich** [comment]
I took a look at your repo. I think it would be much better to have a branch (like feature/lxr-gc) for this in your local repo for people to follow along. You can still rebase or merge from upstream `main` to keep in sync. I am interested in following along and have been trying to clean up the main repo GC code which means you may not like me so much, making your job more difficult.

Also, I am hoping your work will be able to be merged so it needs to be on a branch. https://scala-native.org/en/stable/contrib/contributing.html#general-workflow Also, you may find you want to contribute a fix upstream that is affecting your work downstream so rather than including that in you branch, you could create a pull request.

Looks like a great project!

**Comment by 641bill** [comment]
> I took a look at your repo. I think it would be much better to have a branch (like feature/lxr-gc) for this in your local repo for people to follow along. You can still rebase or merge from upstream `main` to keep in sync. I am interested in following along and have been trying to clean up the main repo GC code which means you may not like me so much, making your job more difficult.
> 
> Also, I am hoping your work will be able to be merged so it needs to be on a branch. https://scala-native.org/en/stable/contrib/contributing.html#general-workflow Also, you may find you want to contribute a fix upstream that is affecting your work downstream so rather than including that in you branch, you could create a pull request.
> 
> Looks like a great project!

Thanks for the suggestions! Indeed, I probably should have created a feature branch for this in the beginning. Now I have created it and I will perform all changes there.
