### ISSUE TITLE
Complete support for Zip

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#932]
- [x] Support java.util.zip.GZIP{Input, Output}Stream (#907)
- [x] Support java.util.zip.Checked{Input, Output}Stream (#933, https://github.com/Duhemm/scala-native/commit/8115a185cc53747de5f08cfdc5aa5582f1e491e1)
- [x] Support for java.util.zip.{ZipFile, ZipEntry} (#935, https://github.com/Duhemm/scala-native/commit/66b12d2d22583e570a0b72f616efd25d20ce6d2e)
- [x] Support java.util.zip.Adler32 (#743, https://github.com/Duhemm/scala-native/commit/b57b0d1634200f1e8e4f8f229c390ea879e694e9)
- [x] Support java.util.zip.Zip{Input, Output}Stream (https://github.com/Duhemm/scala-native/commit/d2da3f87229c021c5c1fb179d5e410e446704a1f)
- [x] Support java.io.PushbackInputStream (#931, https://github.com/Duhemm/scala-native/commit/4ac03ece2504d049436b8cfc3b45696cb386f275)
- [x] Support manipulating JAR files with java.util.jar (#942, https://github.com/Duhemm/scala-native/commit/a08c02040a3a423dafbd0b1209330f0f8a02bb8a)
- [ ] Support for `java.util.jar.Jar{Input, Output}Stream` (#966, https://github.com/Duhemm/scala-native/commit/64de30caff8af93de247a456689d520cf86d2397)
- [x] Open an issue to track that we don't verify JAR signatures at the moment. (#956)
